### ISSUE TITLE
目前已经购买的部分和金额报表，硬件组悠着点

### ISSUE THREAD

**Issue by Glazysnow** [ly0koS/EnvControl-Hardware#17]
![image](https://user-images.githubusercontent.com/50073838/59340116-f4b91a00-8d37-11e9-9097-d488937b84f5.png)

**Comment by Glazysnow** [comment]
硬件组报给我66样一共加起来快200件东西，这日子没法过啦！

**Comment by Glazysnow** [comment]
@zhangshiong123 龙哥你看我这条命值多少电容电阻？

**Comment by zhangshiong123** [comment]
你的命怎么能够用电阻电容来比较   我看你的一根头发丝就够了
