### ISSUE TITLE
元器件清单（部分）

### ISSUE THREAD

**Issue by zoupei2019** [ly0koS/EnvControl-Hardware#5]
[ProjectEnv-Hardware.xlsx](https://github.com/ly0koS/EnvControl-Hardware/files/3255390/ProjectEnv-Hardware.xlsx)

**Comment by Glazysnow** [comment]
![image](https://user-images.githubusercontent.com/50073838/59015652-0ef38380-8872-11e9-9bba-8889a72a544e.png)
![image](https://user-images.githubusercontent.com/50073838/59015672-187ceb80-8872-11e9-83cb-7b41f97bf6b8.png)

**Comment by Glazysnow** [comment]
@zoupei2019
