### ISSUE TITLE
IO口电压

### ISSUE THREAD

**Issue by zhangshiong123** [ly0koS/EnvControl-Hardware#6]
外接传感器的IO口电压是多少呀

**Comment by ly0koS** [comment]
SGP30=1.8V(1.62V-1.98V)
GY-30=3V-5V

**Comment by Glazysnow** [comment]
![TIM图片20190606152443](https://user-images.githubusercontent.com/50073838/59014462-414fb180-886f-11e9-814d-cedb7a3f6ae8.png)

**Comment by Glazysnow** [comment]
![image](https://user-images.githubusercontent.com/50073838/59014506-647a6100-886f-11e9-8714-378c6855afef.png)

**Comment by Glazysnow** [comment]
![image](https://user-images.githubusercontent.com/50073838/59014543-778d3100-886f-11e9-8199-b8cbacde54b1.png)

**Comment by Glazysnow** [comment]
![image](https://user-images.githubusercontent.com/50073838/59014626-a7d4cf80-886f-11e9-9e85-079e6445e7cd.png)

**Comment by Glazysnow** [comment]
![image](https://user-images.githubusercontent.com/50073838/59014774-f4b8a600-886f-11e9-902f-b9173138f203.png)
CCS811我没有找到他的工作电压，建议查一下他的技术文档，应该是有的

**Comment by Glazysnow** [comment]
![image](https://user-images.githubusercontent.com/50073838/59014824-19148280-8870-11e9-9a1e-215ae1b05b13.png)

**Comment by Glazysnow** [comment]
硬件组最帅！

**Comment by Glazysnow** [comment]
其他的应该都在技术文档里，在咱们群里有两个文件，第一个是所有元器件的技术文档，第二个是漏掉的一个元器件的技术文档。

**Comment by Glazysnow** [comment]
@zhangshiong123
